version: '3.8'

services:
  api:
    build: .
    container_name: gagarin_api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/gagarin_db

  mongo:
    image: mongo:latest
    container_name: gagarin_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
